services:
  sera:
    container_name: sera
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "5000"
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
